"fuzzy-pods": Improve UX when aborting fzf.

diff --git a/bin/fuzzy-pods b/bin/fuzzy-pods
--- a/bin/fuzzy-pods
+++ b/bin/fuzzy-pods
@@ -117,6 +117,8 @@ INITIAL_INPUT=$(eval "$FZF_DEFAULT_COMMAND")
 
 [ -z "$INITIAL_INPUT" ] && exit 2
 
+set +e
+
 # CTRL+Z process suspension is suppressed as it doesn't work properly
 # (see <https://github.com/junegunn/fzf/issues/2289>).
 FZF_OUTPUT=$(\
@@ -130,6 +132,20 @@ FZF_OUTPUT=$(\
     --prompt "$(kubectl config current-context | sed 's/-context$//')> " \
     --query="$1" \
 )
+FZF_STATUS="$?"
+
+if [ "$FZF_STATUS" != 0 ]; then
+  # Allow this script to exit cleanly if fzf exits with a return code of
+  # 130, signalling that it was aborted or interrupted by the user.
+  if [ "$FZF_STATUS" = 130 ]; then
+    exit
+  else
+    exit $FZF_STATUS
+  fi
+fi
+
+set -e
+
 SELECTED_ACTION=$(echo "$FZF_OUTPUT" | head -1)
 SELECTED_ITEM=$(echo "$FZF_OUTPUT" | tail -1)
 
